// src/routes/terms/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	
	onMount(() => {
		// Update page title
		document.title = 'Terms of Service - The KPS Group';
	});
</script>

<svelte:head>
	<title>Terms of Service - The KPS Group</title>
	<meta name="description" content="Terms of Service for The KPS Group. Read our terms and conditions for using our services." />
</svelte:head>

<div class="min-h-screen bg-white">
	<div class="container mx-auto px-4 py-16 max-w-4xl">
		<!-- Header -->
		<div class="text-center mb-12">
			<h1 class="text-4xl md:text-5xl font-bold text-navy mb-4">Terms of Service</h1>
			<p class="text-lg text-slate-600">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
		</div>

		<!-- Content -->
		<div class="prose prose-lg max-w-none">
			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">1. Agreement to Terms</h2>
				<p class="text-slate-700 mb-4">
					By accessing and using the services provided by The KPS Group ("we," "our," or "us"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these terms, you may not access our services.
				</p>
				<p class="text-slate-700">
					These Terms apply to all visitors, users, and others who access or use our services.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">2. Description of Services</h2>
				<p class="text-slate-700 mb-4">
					The KPS Group provides business services including but not limited to:
				</p>
				<ul class="list-disc pl-6 text-slate-700 mb-4">
					<li>Brand development and identity design</li>
					<li>Website development and design</li>
					<li>Bookkeeping and accounting services</li>
					<li>Payroll and HR compliance services</li>
					<li>Business consulting and operations optimization</li>
					<li>Technology stack audits and custom software development</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">3. User Accounts and Registration</h2>
				<p class="text-slate-700 mb-4">
					When you create an account with us, you must provide accurate, complete, and current information. You are responsible for safeguarding your account credentials and for all activities that occur under your account.
				</p>
				<p class="text-slate-700">
					You agree to notify us immediately of any unauthorized use of your account or any other breach of security.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">4. Payment Terms</h2>
				<p class="text-slate-700 mb-4">
					Payment terms for our services are as follows:
				</p>
				<ul class="list-disc pl-6 text-slate-700 mb-4">
					<li>Payment is due upon receipt of invoice unless otherwise agreed in writing</li>
					<li>We accept payment by credit card, bank transfer, or other methods as specified</li>
					<li>Late payments may result in suspension of services</li>
					<li>All fees are non-refundable unless otherwise specified in a written agreement</li>
					<li>Prices are subject to change with 30 days written notice</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">5. Intellectual Property Rights</h2>
				<p class="text-slate-700 mb-4">
					The content, features, and functionality of our services are owned by The KPS Group and are protected by copyright, trademark, and other intellectual property laws.
				</p>
				<p class="text-slate-700 mb-4">
					For custom work created for clients:
				</p>
				<ul class="list-disc pl-6 text-slate-700 mb-4">
					<li>Final deliverables become client property upon full payment</li>
					<li>We retain the right to use work for portfolio and marketing purposes</li>
					<li>Source files and working materials remain our property unless specified in writing</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">6. Prohibited Uses</h2>
				<p class="text-slate-700 mb-4">You may not use our services:</p>
				<ul class="list-disc pl-6 text-slate-700 mb-4">
					<li>For any unlawful purpose or to solicit others to perform unlawful acts</li>
					<li>To violate any international, federal, provincial, or state regulations, rules, laws, or local ordinances</li>
					<li>To infringe upon or violate our intellectual property rights or the intellectual property rights of others</li>
					<li>To harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate</li>
					<li>To submit false or misleading information</li>
					<li>To upload or transmit viruses or any other type of malicious code</li>
					<li>To collect or track the personal information of others</li>
					<li>To spam, phish, pharm, pretext, spider, crawl, or scrape</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">7. Limitation of Liability</h2>
				<p class="text-slate-700 mb-4">
					In no event shall The KPS Group, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
				</p>
				<ul class="list-disc pl-6 text-slate-700 mb-4">
					<li>Your use or inability to use our services</li>
					<li>Any unauthorized access to or use of our servers and/or any personal information stored therein</li>
					<li>Any interruption or cessation of transmission to or from our services</li>
					<li>Any bugs, viruses, trojan horses, or the like that may be transmitted to or through our services</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">8. Disclaimer of Warranties</h2>
				<p class="text-slate-700 mb-4">
					Our services are provided on an "AS IS" and "AS AVAILABLE" basis. The KPS Group makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">9. Indemnification</h2>
				<p class="text-slate-700 mb-4">
					You agree to defend, indemnify, and hold harmless The KPS Group and its licensees and service providers from any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees arising out of or relating to your violation of these Terms or your use of our services.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">10. Termination</h2>
				<p class="text-slate-700 mb-4">
					We may terminate or suspend your account and bar access to our services immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.
				</p>
				<p class="text-slate-700">
					If you wish to terminate your account, you may simply discontinue using our services.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">11. Governing Law</h2>
				<p class="text-slate-700 mb-4">
					These Terms shall be interpreted and governed by the laws of the State of Texas, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">12. Changes to Terms</h2>
				<p class="text-slate-700 mb-4">
					We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days notice prior to any new terms taking effect.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">13. Severability</h2>
				<p class="text-slate-700 mb-4">
					If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-2xl font-bold text-navy mb-4">14. Contact Information</h2>
				<p class="text-slate-700 mb-4">
					If you have any questions about these Terms of Service, please contact us:
				</p>
				<div class="bg-slate-50 p-6 rounded-lg">
					<p class="text-slate-700 mb-2"><strong>The KPS Group</strong></p>
					<p class="text-slate-700 mb-2">Email: <a href="mailto:legal@thekpsgroup.com" class="text-gold hover:text-gold-600">legal@thekpsgroup.com</a></p>
					<p class="text-slate-700 mb-2">Phone: <a href="tel:469-458-6966" class="text-gold hover:text-gold-600">469-458-6966</a></p>
					<p class="text-slate-700">Address: Dallas, Texas, United States</p>
				</div>
			</section>
		</div>

		<!-- Back to Home -->
		<div class="text-center mt-12">
			<a href="/" class="inline-block bg-navy text-white px-8 py-3 rounded-lg font-semibold hover:bg-navy-600 transition-colors">
				Back to Home
			</a>
		</div>
	</div>
</div>

<style>
	.prose h2 {
		color: #00438c;
		margin-top: 2rem;
		margin-bottom: 1rem;
	}
	
	.prose h3 {
		color: #00438c;
		margin-top: 1.5rem;
		margin-bottom: 0.75rem;
	}
	
	.prose ul {
		margin-bottom: 1rem;
	}
	
	.prose li {
		margin-bottom: 0.5rem;
	}
</style>

// app/terms/page.tsx
import { headers } from 'next/headers';
import { resolveBrand } from '@kps/config';

export const metadata = {
  title: 'Terms of Service',
  description: 'The terms governing your use of our services, agreements, and limitations of liability.'
};

export default async function TermsPage() {
  const headersList = await headers();
  const brandKey = headersList.get('x-brand') || 'kps-group';
  const brand = resolveBrand(undefined, brandKey as any);

  return (
    <section className="py-20 bg-neutral-50">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-bold text-neutral-900 mb-6">
              Terms of Service
            </h1>
            <p className="text-xl text-neutral-600">
              Last updated: December 2024
            </p>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-neutral-200 p-8">
            <div className="prose prose-neutral max-w-none">
              <h2 className="text-2xl font-bold text-neutral-900 mb-6">
                Agreement to Terms
              </h2>
              <p className="text-neutral-700 mb-4">
                By accessing and using the services provided by The KPS Group (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;), 
                you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you disagree with any 
                part of these terms, you may not access our services.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Services Description
              </h2>
              <p className="text-neutral-700 mb-4">
                The KPS Group provides professional business services including but not limited to:
              </p>
              <ul className="list-disc pl-6 text-neutral-700 mb-6">
                <li>Business consulting and strategic advisory services</li>
                <li>Financial services including bookkeeping and accounting</li>
                <li>Payroll and human resources solutions</li>
                <li>Brand development and marketing services</li>
                <li>Technology services and IT consulting</li>
                <li>Business automation and process optimization</li>
                <li>Compliance and regulatory advisory services</li>
              </ul>
              <p className="text-neutral-700 mb-4">
                The specific services provided will be outlined in separate service agreements or statements of work.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                User Responsibilities
              </h2>
              <p className="text-neutral-700 mb-4">
                You agree to:
              </p>
              <ul className="list-disc pl-6 text-neutral-700 mb-6">
                <li>Provide accurate, complete, and current information</li>
                <li>Maintain the security of your account information and credentials</li>
                <li>Use our services in compliance with applicable laws and regulations</li>
                <li>Not engage in any fraudulent, harmful, or illegal activities</li>
                <li>Respect intellectual property rights and proprietary information</li>
                <li>Cooperate with reasonable requests for information and documentation</li>
                <li>Maintain appropriate insurance coverage as required by law</li>
                <li>Notify us promptly of any material changes to your business or circumstances</li>
              </ul>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Payment Terms
              </h2>
              <p className="text-neutral-700 mb-4">
                Payment terms will be specified in individual service agreements. All fees are due according to the agreed-upon schedule. 
                Late payments may result in service suspension or termination. We reserve the right to charge interest on overdue amounts 
                at the rate of 1.5% per month or the maximum rate permitted by law.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Intellectual Property
              </h2>
              <p className="text-neutral-700 mb-4">
                All content, trademarks, service marks, trade names, logos, and intellectual property on our website and in our services 
                are owned by The KPS Group or our licensors. You may not use, reproduce, distribute, or create derivative works of this 
                content without our written permission.
              </p>
              <p className="text-neutral-700 mb-4">
                Work product created specifically for you under a service agreement will be subject to the terms of that agreement.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Confidentiality
              </h2>
              <p className="text-neutral-700 mb-4">
                Both parties agree to maintain the confidentiality of proprietary and sensitive information shared during the course of 
                our engagement. This obligation survives termination of these Terms and any service agreements.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Limitation of Liability
              </h2>
              <p className="text-neutral-700 mb-4">
                To the maximum extent permitted by law, The KPS Group shall not be liable for any indirect, incidental, special, 
                consequential, or punitive damages arising from your use of our services, including but not limited to lost profits, 
                lost data, business interruption, or any other commercial damages or losses.
              </p>
              <p className="text-neutral-700 mb-4">
                Our total liability to you for any claims arising from these Terms or our services shall not exceed the amount paid 
                by you to us in the twelve (12) months preceding the claim.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Indemnification
              </h2>
              <p className="text-neutral-700 mb-4">
                You agree to indemnify, defend, and hold harmless The KPS Group and its officers, directors, employees, and agents 
                from and against any claims, damages, losses, liabilities, costs, and expenses arising from your use of our services 
                or violation of these Terms.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Disclaimers
              </h2>
              <p className="text-neutral-700 mb-4">
                Our services are provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express or implied. 
                We disclaim all warranties, including but not limited to warranties of merchantability, fitness for a particular purpose, 
                and non-infringement.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Termination
              </h2>
              <p className="text-neutral-700 mb-4">
                We may terminate or suspend your access to our services immediately, without prior notice, for any reason, including 
                breach of these Terms. Upon termination, your right to use our services will cease immediately, and you must return 
                or destroy any confidential information in your possession.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Force Majeure
              </h2>
              <p className="text-neutral-700 mb-4">
                Neither party shall be liable for any failure or delay in performance under these Terms due to circumstances beyond 
                their reasonable control, including but not limited to acts of God, natural disasters, war, terrorism, government 
                actions, or other events of force majeure.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Governing Law and Jurisdiction
              </h2>
              <p className="text-neutral-700 mb-4">
                These Terms shall be governed by and construed in accordance with the laws of the State of Texas, without regard to 
                its conflict of law provisions. Any disputes arising from these Terms or our services shall be resolved in the state 
                or federal courts located in Travis County, Texas.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Severability
              </h2>
              <p className="text-neutral-700 mb-4">
                If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated 
                to the minimum extent necessary so that these Terms will otherwise remain in full force and effect.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Entire Agreement
              </h2>
              <p className="text-neutral-700 mb-4">
                These Terms constitute the entire agreement between you and The KPS Group regarding the subject matter hereof and 
                supersede all prior or contemporaneous communications, proposals, and agreements, whether oral or written.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Changes to Terms
              </h2>
              <p className="text-neutral-700 mb-4">
                We reserve the right to modify these Terms at any time. We will notify users of any material changes by posting the 
                new Terms on our website and updating the &quot;Last updated&quot; date. Your continued use of our services after such 
                changes constitutes acceptance of the new Terms.
              </p>

              <h2 className="text-2xl font-bold text-neutral-900 mt-12 mb-6">
                Contact Information
              </h2>
              <p className="text-neutral-700 mb-4">
                If you have questions about these Terms of Service, please contact us:
              </p>
              <div className="bg-neutral-50 p-4 rounded-lg">
                <p className="text-neutral-700">
                  <strong>The KPS Group</strong><br />
                  5900 Balcones Drive, Suite 100<br />
                  Austin, Texas 78731<br />
                  <strong>Email:</strong> {brand.contact.email}<br />
                  <strong>Phone:</strong> {brand.contact.phone}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
